### ISSUE TITLE
TypeError: Unsupported flake ref type for private flake repos

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [jessestricker/nix-flake-update#82]
Hi @jessestricker 

thanks for the nix flake plugin. It works like charm with public flakes but I encountered an error dealing with private repo flakes.

https://github.com/GeorgesAlkhouri/nixos-configs/actions/runs/3911211517/jobs/6684337146

```
Run jessestricker/nix-flake-update@v1
Updating the flake's inputs...
Output of `nix flake update`

/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/lockfile.ts:133
  throw new TypeError("Unsupported flake ref type");
^
TypeError: Unsupported flake ref type
    at getFlakeRefUri (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/lockfile.ts:133:1)
    at /home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/report.ts:54:1
    at pairTransform (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/util/itererables.ts:11:1)
    at Array.map (<anonymous>)
    at transformValues (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/util/itererables.ts:16:1)
    at generateBodyDiffingSection (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/report.ts:53:1)
    at generateBody (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/report.ts:43:1)
    at generateReport (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/report.ts:28:1)
    at main (/home/runner/work/_actions/jessestricker/nix-flake-update/v1/src/main.ts:31:1)
```

Here is my full [github action](https://github.com/GeorgesAlkhouri/nixos-configs/blob/main/.github/workflows/update-action.yml) where you can see I provided the needed ssh key.

Nix supports  private flakes if the ssh-agent have the appropriated private ssh key to fetch the repo of course.

So at a first glance the error occurred because of the ssh part in the [flake](https://github.com/GeorgesAlkhouri/nixos-configs/blob/main/flake.nix) URI I think.

```
    nixosSecrets = {
      url = "git+ssh://git@github.com/GeorgesAlkhouri/nixos-secrets.git";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

**Comment by jessestricker** [comment]
Thank you for reporting this issue.

Yes, the scheme of the input's url is not yet supported, so far only GitHub flake references are:

https://github.com/jessestricker/nix-flake-update/blob/0eb556c581d875939361c17ee4d66b8d11cb819e/src/lockfile.ts#L123-L134

I will look into implementing more flake reference types if they're easy enough to incorporate.

**Comment by GeorgesAlkhouri** [comment]
Thanks a lot, that would be awesome.

**Comment by jessestricker** [comment]
The purpose of this action was to print a more detailed report on the changes made by `nix flake update`. This can only really be done for some types for flake references, e.g. GitHub, GitLab, etc. where there is a website we can link to that compares two commits.

For a random `git://`-URL, the action can't possibly link to a compare page. It would have to keep a list of well-known websites and use sophisticated URL parsing to match against. This would be even harder or impossible for other types of URLs.

So after a bit of pondering, I think I am going to archive this project and refer you an actively maintained alternative like <https://github.com/DeterminateSystems/update-flake-lock>.
